#docker-compose file
version: '1.0.0'

services:
  ubuntu-network:
    container_name: ubuntu-network-3
    image: tukho/ubuntu-network:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
  ubuntu-network-2:
    container_name: ubuntu-network-4
    image: tukho/ubuntu-network:1.0.0
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    external:
      name: test-network